### PR TITLE
Fix travis failed issue.

### PR DESCRIPTION
**Pull request by lzbj**
Make package dependency to https://github.com/lzbj/go-whisk.git
Before the go whisk client officially available on Github.

### CODE REVIEW

**Comment by paulcastro** [comment]
Let me check with the CLI maintainers to see if we can separate out the CLI framework as a Go dependency

**Comment by lzbj** [comment]
@paulcastro, I made it here: https://github.com/lzbj/go-whisk.git. It's a temp solution before Openwhisk go cli split out.

**Comment by lzbj** [comment]
Thank you Paul, hope you can get it split. The i18n code in this pr is necessary for the project to compile and test.

**Comment by paulcastro** [comment]
I opened issue #1480 in the OpenWhisk repo for moving the go-whisk library to its own repo.

**Pull request merged**
